# safelist
branches:
  only:
  - master
  - stable
  
# Project settings
language: node_js
node_js:
  - 10
  - 7
before_script:
  - npm install -g grunt
  - npm install -g codecov
  - npm install
script: 
  - grunt
  - codecov
